#!/bin/bash -e

if ! type -P auracle &>/dev/null; then
  echo "error: \`auracle' binary required but not found in PATH" >&2
  exit 1
fi

mkdir -p db aur_sourcedb

mapfile -t pkgs < <(curl -s https://aur.archlinux.org/packages.gz | gzip -cd | grep -v '^#')

# auracle's rawinfo output will likely be multiple result objects due to
# request size limitations of the AUR. It might be nice if auracle were to
# merge this for us, but that's sort of not-the-point of the raw methods. It
# does give us a result-per-line though, so we can just split on that.
auracle rawinfo "${pkgs[@]}" |
  split --lines=1 --suffix-length=3 - aur_sourcedb/out.

for f in aur_sourcedb/*; do
  build/json_to_protobuf "$f" "$PWD/db" &
done
wait

printf 'done: %s entries added to DB\n' "${#pkgs[@]}"
